server.port=9001
spring.main.banner-mode=off
logging.level.org.springframework=ERROR
logging.level.com.wesovilabs.workshops.graphql=DEBUG

spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://database:5432/workshop
spring.datasource.username=workshop
spring.datasource.password=graphql
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = validate
spring.datasource.continue-on-error=true