server:
  port: 9001
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5456/workshop
    username: workshop
    password: graphql
    continue-on-error: true
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
logging:
  level:
    org.springframework: WARN
    com.wesovilabs.workshops.graphql: DEBUG
graphql:
  tools:
    introspection-enabled: true
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    subscriptions:
      websocket:
        enabled: true
        path: /subscriptions
graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true
  pageTitle: Wesovilabs
