version: "2"

services:

  api:
    image: wesovilabs/workshop-graphql-java:local
    restart: always
    ports:
      - 9001:9001
    depends_on:
      - database
    links:
      - database
    volumes:
      - ./api/application.yaml:/opt/config/application.yaml

  database:
    image: "postgres:10-alpine"
    restart: always
    ports:
      - 5456:5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "workshop"
      POSTGRES_PASSWORD: graphql